config/routes.rb
Rails.application.routes.draw do
  resources :emails
  resources :profiles
  resources :emails
  resources :reminds do
    collection do
      delete 'destroy_multiple'
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root 'startpage#index' #root page
  
  devise_for :users, :path_prefix => 'd'
  resources :users
  
  match '/users', to: 'users#index', via: 'get' #show list of user for admin
  match '/users/:id', to: 'users#show', via: 'get' #allows to view your own account
  
  get '/checkprofile' => 'profiles#checkprofile' #route to checkprofile method
  get '/completed' => 'reminds#completed'
  get '/listallreminders' => 'search#list_all_reminders'
  get '/listallsentreminders' => 'search#list_all_sent_reminders'
  
  ### Contact us form route ###
  match '/contacts',     to: 'contacts#new',             via: 'get'
  resources "contacts", only: [:new, :create]
  
end

app/models/profile.rb
# Class name: Profile
# Version: 0.3
# Date 2016/10
# @author Aleksandr Kuriackovskij, x15029476

class Profile < ApplicationRecord
  belongs_to :user
  has_one :email
  accepts_nested_attributes_for :email
  
  after_create :check_email
  
  validates :age, length: { maximum: 2 }, presence: true
  validates :name, presence: true
  validates :lastname, presence: true
  
  private
  
  #After profile creation, below method is checking if e-mail already exist in Email table, and if so, updates Foreign Key with a new value (profile.id)
  #This method is required in order to link reminders with account. Here, reminders which were created by e-mails before account/profile is created.
  def check_email
    ex_address = User.find_by_id(self.user_id).email
    if Email.exists?(email: ex_address)
      email_record_id = Email.find_by_email(ex_address).id
      Email.update(email_record_id, :profile_id => self.id)
    else
      email = Email.new({:email => ex_address, :profile_id => self.id})
      email.save
    end
  end
  
end

app/controllers/profiles_controller.rb
# Class name: ProfilesController
# Version: 0.2
# Date 2016/11
# @author Aleksandr Kuriackovskij, x15029476

class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!
  before_filter :isadmin, :only => [:destroy, :index]
  
  #Method which verifies if current user is admin and allows to destroy profiles
  def isadmin
    unless current_user && current_user.admin?
      render :forbidden
    end
  end
  
  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
    @profile.user_id = current_user.id #creates profile with the same id as initial account (in devise) has
  end

  # GET /profiles/1/edit
  def edit
  end

  ##############=checkprofile= method#############
  #Method which check if logged user has a profile
  ################################################
  def checkprofile
    profile = Profile.find_by_user_id(current_user.id)
    if profile.nil?
      redirect_to "/profiles/new"
    else
      @profile = Profile.find_by_user_id(current_user.id)
      redirect_to "/reminds"
    end
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(profile_params)

    respond_to do |format|
      if @profile.save
          format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
          format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:name, :lastname, :age, :user_id, :timezone)
    end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.erb
<%= form_for(profile) do |f| %>
  <% if profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="profile" style="text-align:left;">
    <%= f.label :name %>
    <span style="padding-left:49px;"><%= f.text_field :name %></span>
  </div>

  <div class="profile" style="text-align:left;">
    <%= f.label :lastname %>
    <span style="padding-left:20px;"><%= f.text_field :lastname %></span>
  </div>

  <div class="profile" style="text-align:left;">
    <%= f.label :age %>
    <span style="padding-left:63px;"><%= f.number_field :age, min: 0, max: 99, :size => "5" %></span>
  </div>
  
  <div class="profile" style="text-align:left;">
    <%= f.label :location %>
    <span style="padding-left:29px;"><%= f.time_zone_select :timezone, nil, default: Time.zone.name %></span>
  </div>
  
    <%= f.text_field :user_id, value: User.find_by_id(@profile.user_id).id, :hidden => true  %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<% if current_user.profile == @profile or current_user.admin? %> <!-- Checking if user is admin or profile owner. Only they are able to edit profile. -->
    <h1>Editing Profile</h1>
    <div class="pad">
        <%= render 'form', profile: @profile %>
    </div>
    <div class="optlink">
        <%= link_to 'Back', profiles_path %>
    </div>
<% else %>
    <h2>You are not authorized to edit this profile.</h2>
<% end %>
</div>

app/views/profiles/forbidden.html.erb
<h2>This actions is not allowed.</h2>

app/views/profiles/index.html.erb
<p id="notice"><%= notice %></p>

<h2>Profiles list(<span style="color:red; font-family:Arial;">admin</span>)</h2>

<div class="pad">
  <table>
    <thead>
        <tr style="text-decoration: underline;">
          <th>Name</th>
          <th>Lastname</th>
          <th>Age</th>
          <th>Location</th>
          <th>User ID</th>
          <th colspan="3"></th>
        </tr>
      </thead>
    
      <tbody>
        <% @profiles.each do |profile| %>
          <tr>
            <td><%= profile.name %></td>
            <td><%= profile.lastname %></td>
            <td><%= profile.age %></td>
            <td><%= profile.timezone %></td>
            <td><%= profile.user_id %></td>
            <td><%= link_to 'Show', profile %></td>
            <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<br>

app/views/profiles/new.html.erb
<h1>New Profile</h1>
<div class="pad">
    <%= render 'form', profile: @profile %>
</div>
<div class="optlink">
    <%= link_to 'Back', profiles_path %>
</div>

app/views/profiles/show.html.erb
<div class="pad">
  <p id="notice"><%= notice %></p>
  
  <% if current_user.profile == @profile or current_user.admin? %> <!--Only profile owner or admin are allowed to view profile -->
    <p>
      <strong>Name:</strong>
      <%= @profile.name %>
    </p>
    
    <p>
      <strong>Lastname:</strong>
      <%= @profile.lastname %>
    </p>
    
    <p>
      <strong>Age:</strong>
      <%= @profile.age %>
    </p>
    
    <p>
      <strong>User ID:</strong>
      <%= @profile.user_id %>
    </p>
    
    <p>
      <strong>Location:</strong>
      <%= @profile.timezone %>
    </p>
  <% else %>
    <h2>You are not authorized to view this profile.</h2>
  <% end %>
</div>
<div class="optlink">
  <%= link_to 'Edit profile', edit_profile_path(@profile) %>
  <% if current_user.admin? %>
    | <%= link_to 'List profiles', profiles_path %>
  <% end %>
</div>