config/routes.rb
Rails.application.routes.draw do
  resources :emails
  resources :profiles
  resources :emails
  resources :reminds do
    collection do
      delete 'destroy_multiple'
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root 'startpage#index' #root page
  
  devise_for :users, :path_prefix => 'd'
  resources :users
  
  match '/users', to: 'users#index', via: 'get' #show list of user for admin
  match '/users/:id', to: 'users#show', via: 'get' #allows to view your own account
  
  get '/checkprofile' => 'profiles#checkprofile' #route to checkprofile method
  get '/completed' => 'reminds#completed'
  get '/listallreminders' => 'search#list_all_reminders'
  get '/listallsentreminders' => 'search#list_all_sent_reminders'
  
  ### Contact us form route ###
  match '/contacts',     to: 'contacts#new',             via: 'get'
  resources "contacts", only: [:new, :create]
  
end

app/models/remind.rb
# Class name: Remind
# Version: 1.3
# Date 2016/11
# @author Aleksandr Kuriackovskij, x15029476

require 'my_logger'

class Remind < ApplicationRecord

#Validations and callbacks
belongs_to :email
validate :date_cannot_be_in_the_past                                             #Validating that date cannot be past only on create. When updating record - it won't require
after_create :send_confirmation                                                   #Invoke method send_confirmation after reminder is created.

#Method checks if date and time are not less than current time.
def date_cannot_be_in_the_past
  errors.add(:schedule, "must be higher or equal to today") if !schedule.blank? && schedule < Time.now
end

def self.get_email(message)
  #If statement for getting user's timezone and setting appropriate time based on it
  if (Email.exists? email: message.from.first) && (Profile.exists? id: Email.find_by_email(message.from.first).profile_id)
    tz = Profile.find_by_id(Email.find_by_email(message.from.first).profile_id).timezone
  else
  #Default timezone
    tz = "UTC"
  end
  timezone = Time.now.in_time_zone(tz).strftime('%z')
  #Declaring dates variables for logging date of reminder using word notation instead of digits.
  Time.zone = tz
  today = Time.now.in_time_zone(tz).to_date
  today_s = today.to_s+" "
  tomorrow = (today + 1.day).to_s+" "
  nextweek = (today + 1.week).to_s+" "
  nextmonth = (today + 1.month).to_s+" "
  nextyear = (today + 1.year).to_s+" "
  #Important part of code where exceptions more likely to occur if user sends bad subject, past date etc. 
  begin
	#Verifying hash delimiter is in the subject
    if message.subject.include? "#"
	  #Extracting email title from subject after '#' sign	
	  title_arg = message.subject.partition('#').last
	  #Extracting part before '#' where date and time suppose to be
      timeparse = message.subject.partition('#').first
	  #Verifying time delimiter. If between hour and minute is dot ".", replace it with colon ":"	  
      if timeparse.include? "."
        timeparse.gsub!('.', ':')
      end
      #Converting extracted time to readable for app datetime format
      time_non_converted = timeparse.to_datetime
	  #Converting datetime to time only
      time_sched = time_non_converted.strftime("%H:%M:00")
      
      #getting reminder date from word notation, or, in final, from digital notation.
      if message.subject.partition('#').first.downcase.include? "today"
        sched_non_converted = (today_s + time_sched).to_datetime
        sched_arg = sched_non_converted.change(:offset => -timezone)
      elsif message.subject.partition('#').first.downcase.include? "tomorrow"
        sched_non_converted = (tomorrow + time_sched).to_datetime
        sched_arg = sched_non_converted.change(:offset => -timezone)
      elsif message.subject.partition('#').first.downcase.include? "week"
        sched_non_converted = (nextweek + time_sched).to_datetime
        sched_arg = sched_non_converted.change(:offset => -timezone)
      elsif message.subject.partition('#').first.downcase.include? "month"
        sched_non_converted = (nextmonth + time_sched).to_datetime
        sched_arg = sched_non_converted.change(:offset => -timezone)
      elsif message.subject.partition('#').first.downcase.include? "year"
        sched_non_converted = (nextyear + time_sched).to_datetime
        sched_arg = sched_non_converted.change(:offset => -timezone)
      else
        digitaldate = message.subject.partition('#').first.to_datetime.strftime("%Y-%m-%d")
        sched_non_converted = (digitaldate+" "+time_sched).to_datetime
        sched_arg = sched_non_converted.change(:offset => -timezone)
      end
      
      #Calling logreminder method if no exceptions have been occured
      logreminder(message, title_arg, sched_arg)
        
    else
      Autoreply.send_no_hash(message)
    end
  ##################################################
  ############# Rescuing exceptions ################
  ##################################################
  rescue ArgumentError
    Autoreply.send_date_missing(message)
  rescue Encoding::UndefinedConversionError
    Autoreply.bad_encoding(message)
  rescue Exception => error_message
    Autoreply.bad_delivery(message)
    ################################################
    ## Logger to log unknown unhandled exceptions ##
    ################################################
    catch_log = MyLogger.instance
    catch_log.logException("NEW ERROR LOGGED! - " + Time.now.to_s)
    catch_log.logException("#################---------------------################")
    catch_log.logException(error_message)
    catch_log.logException("######################################################")
    
  end
end

#Reminders check method which checks what reminders have to be processed right now.
def self.check_reminder
  time = Time.now.strftime("%Y-%m-%d %H:%M:00")
  sendnow = Remind.where("schedule <= ?", time).where(:sent => nil) #Find reminders where scheduled time is less then current time and which weren't sent before.
  #Loop through all reminders which conforms to the above condition
  sendnow.each do |remind|
  #Invoke method which is responsible for sending reminder
    Autoreply.send_reminder(remind)
  end
end

private
#Reminders logging method which is called from get_email method
def self.logreminder(message, title_arg, sched_arg)
    #Starting catching exceptions from here
    begin
	  #Checking if sender's e-mails address is already in database, and create if not exists
      if Email.where(:email => message.from.first).blank?
        Email.create! email: message.from.first
        email_id = Email.find_by_email(message.from.first).id
		#Inserting new reminder into database
        Remind.create! title: title_arg, body: message.html_part.body.decoded, email_id: email_id, schedule: sched_arg
      else
        email_id = Email.find_by_email(message.from.first).id
		#Inserting new reminder into database
        Remind.create! title: title_arg, body: message.html_part.body.decoded, email_id: email_id, schedule: sched_arg
      end
	#If validation unseuccesful, thus time in past, catch exception and call email notification method
    rescue ActiveRecord::RecordInvalid
      Autoreply.past_date(message)
    end
end

  def send_confirmation
    if User.current == nil          #Send confirmation only when user is not logged-on
      Autoreply.send_confirm(self)
    end
  end
  
end

app/controllers/reminds_controller.rb
# Class name: RemindsController
# Version: 1.1
# Date 2016/11
# @author Aleksandr Kuriackovskij, x15029476

class RemindsController < ApplicationController

  before_action :set_remind, only: [:show, :edit, :update, :destroy]
  before_filter :set_timezone

  # GET /reminds
  # GET /reminds.json
  def index
    email_id = Email.find_by_email(current_user.email).id
    @reminds = Remind.where(:email => email_id)
  end

  #The same as index method, but is required for listing past reminders
  def completed
    email_id = Email.find_by_email(current_user.email).id
    @reminds = Remind.where(:email => email_id)
  end
  
  #Setting time zone when any actions in this controller occurs 
  def set_timezone
    tz = Profile.find_by_user_id(current_user.id).timezone
    @timezone = Time.now.in_time_zone(tz).strftime('%z')
    if current_user
      User.current = current_user
    end
  end

  # GET /reminds/1
  # GET /reminds/1.json
  def show
  end

  # GET /reminds/new
  def new
    @remind = Remind.new
    @remind.email_id = Email.find_by_email(current_user.email).id #maps reminder to email ID
  end

  # GET /reminds/1/edit
  def edit
  end

  # POST /reminds
  # POST /reminds.json
  def create
      @remind = Remind.new(remind_params)
      if user_signed_in?
	    #Set time zone for new reminder only if user is logged in. There is another method in Remind class for logging from e-mails.
        user_time = @remind.schedule.to_datetime
        @remind.schedule = user_time.change(:offset => @timezone)
      end

    respond_to do |format|
      if @remind.save
        format.html { redirect_to @remind, notice: 'Reminder was successfully created.' }
        format.json { render :show, status: :created, location: @remind }
      else
        format.html { render :new }
        format.json { render json: @remind.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reminds/1
  # PATCH/PUT /reminds/1.json
  def update
    respond_to do |format|
      if @remind.update(remind_params)
        format.html { redirect_to @remind, notice: 'Reminder was successfully updated.' }
        format.json { render :show, status: :ok, location: @remind }
      else
        format.html { render :edit }
        format.json { render json: @remind.errors, status: :unprocessable_entity }
      end
    end
  end

#Method which delete selected reminders
  def destroy_multiple
    Remind.destroy(params[:reminds])
    respond_to do |format|
      format.html { redirect_to :back, notice:  'Reminder(s) was deleted.' }
      format.json { head :no_content }
    end
  end

  # DELETE /reminds/1
  # DELETE /reminds/1.json
  #def destroy
  #  @remind.destroy
  #  respond_to do |format|
  #    format.html { redirect_to :back, notice: 'Reminder was successfully destroyed.' }
  #    format.json { head :no_content }
  #  end
  #end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_remind
      @remind = Remind.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def remind_params
      params.require(:remind).permit(:email_id, :title, :body, :schedule)
    end
end

app/helpers/reminds_helper.rb
module RemindsHelper
end

app/views/reminds/_form.html.erb
<%= form_for(remind) do |f| %>
  <% if remind.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(remind.errors.count, "error") %> prohibited this reminder from being saved:</h2>

      <ul>
      <% remind.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :email_id, :hidden => true %>
  </div>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title, :size => "70" %>
  </div><br>

  <div class="field main" style="font-weight: 800;">
    <%= f.label :body %>
    <%= f.text_area :body, :class => 'ckeditor' %> <!-- Using ckeditor for creation and editing reminders. Supports HTML and many fonts manipulation features. -->
  </div>

  <div class="field">
   <% Time.use_zone(Profile.find_by_user_id(current_user.id).timezone) do %> <!-- Below code will be affected by user's time zone. It's like a time zone emulation. -->
    <%= f.label :schedule %> <br>
    <%= f.datetime_select :schedule, :start_year => Date.today.year %>
  <% end %>
  </div>
<br>
  <div class="actions">
    <%= f.submit( f.object.new_record? ? "Create Reminder" : "Update Reminder") %>
  </div>
<% end %>

app/views/reminds/completed.html.erb
<p id="notice"><%= notice %></p>
<h1>Past Reminders</h1>
<div class="pad">
  <%= form_tag destroy_multiple_reminds_path, method: :delete do %> <!-- Form for selecting multiple reminders to delete. -->
    <% if @reminds.where(:sent => true).empty? %>
      <h4 style="color:yellow">You don't have any past reminders.</h4>
    <% else %>
      <table>
        <thead>
          <tr style="text-decoration: underline;">
            <th>Select to delete</th>
            <th>Email</th>
            <th>Title</th>
            <th>Was sent to you on</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @reminds.where(:sent => true).each do |remind| %> <!-- List only already sent reminders (where "sent" = true) -->
            <tr>
              <td><%= check_box_tag "reminds[]", remind.id %></td>
              <td><%= Email.find_by_id(remind.email_id).email %></td>
              <td id="titlelink"><%= link_to truncate(remind.title, :length => 50), remind %></td> <!-- Allow only 50 symbols to be displayed in list view. -->
              <% Time.use_zone(Profile.find_by_user_id(current_user.id).timezone) do %>
                <td><%= remind.schedule.strftime("%Y-%m-%d %H:%M:00") %></td>
              <% end %>
              <td><%= link_to 'Edit', edit_remind_path(remind) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <div class="optlink">
    <%= submit_tag "Delete selected", data: { confirm: 'Are you sure want to delete selected?' } %><br>
  <% end %>
<% end %>
<%= link_to "List scheduled reminders", reminds_path %>
<h2><%= link_to 'Create new', new_remind_path %></h2>
</div>

app/views/reminds/edit.html.erb
<% if current_user.email == Email.find_by_id(@remind.email_id).email %> <!-- Allow to edit and create only own reminders -->
    <h1>Editing Reminder</h1>
    <div class="pad">
        <%= render 'form', remind: @remind %>
    </div>
    <div class="optlink">
        <%= link_to 'Back', :back %>
    </div>
<% else %>
    <h2>You are not authorized to edit this reminder.</h2>    
<% end %>

app/views/reminds/forbidden.html.erb
<h2>This actions is not allowed.</h2>

app/views/reminds/index.html.erb
<h1>Scheduled Reminders</h1>
<div class="pad">
  <%= form_tag destroy_multiple_reminds_path, method: :delete do %> <!-- Form for selecting multiple reminders to delete. -->
    <% if @reminds.where(:sent => nil).empty? %>
      <h4 style="color:yellow">You don't have any scheduled reminders.</h4>
    <% else %>
      <table>
        <h3 style="color:green"><%= flash[:notice] %></h3>
        <thead>
          <tr style="text-decoration: underline;">
            <th>Select to delete</th>
            <th>Email</th>
            <th>Title</th>
            <th>Schedule</th>
            <th></th>
            <th></th>
            <th colspan="3"></th>
          </tr>
        </thead>
        
        <tbody>
          <% @reminds.where(:sent => nil).each do |remind| %> <!-- List only scheduled reminders (where "sent" = nil) -->
            <tr>
              <td><%= check_box_tag "reminds[]", remind.id %></td>
              <td><%= Email.find_by_id(remind.email_id).email %></td>
              <td id="titlelink"><%= link_to truncate(remind.title, :length => 50), remind %></td> <!-- Allow only 50 simbols to be displayed in list view. -->
              <% Time.use_zone(Profile.find_by_user_id(current_user.id).timezone) do %>
                <td><%= remind.schedule.strftime("%Y-%m-%d %H:%M:00") %></td>
              <% end %>
              <td><%= link_to 'Edit', edit_remind_path(remind) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  <div class="optlink">
    <%= submit_tag "Delete selected", data: { confirm: 'Are you sure want to delete selected?' } %> <br>
  <% end %>
<% end %>
 <%= link_to 'List past reminders', completed_path %>
<h2><%= link_to 'Create new', new_remind_path %></h2>
</div>

app/views/reminds/listallreminders.html.erb
<html>
  <div class="pad">
    <div id="header_text">
      <h2>List of all Scheduled Reminders(<span style="color:red; font-family:Arial;">admin</span>)</h2><br>
      <h3 style="color:red"><%= flash[:notice] %></h3>
      <%= form_tag(listallreminders_path, :method => "get") do %>
        <%= text_field_tag :search, nil, :placeholder =>"E-mail address" %>
        <%= submit_tag "Search" %>
      <% end %>
    </div><br>
  <%= link_to 'List all past Reminders', listallsentreminders_path %> 
  <%= form_tag destroy_multiple_reminds_path, method: :delete do %> <!-- Form for selecting multiple reminders to delete. -->
  <table>
    <thead style="text-decoration: underline;">
        <th>Select to delete</th>
        <th>Email address</th>
        <th>Subject</th>
        <th>Scheduled for</th>
        <th>Created on</th>
      </tr>
    </thead>
  
      <tbody>
      <% @reminders.where(:sent => nil).each do |reminder| %> <!-- List only scheduled reminders (where "sent" = nil) -->
        <tr>
          <td><%= check_box_tag "reminds[]", reminder.id %></td>
          <td><%= Email.find_by_id(reminder.email_id).email %></td>
          <td><%= truncate(reminder.title, :length => 50) %></td> <!-- Allow only 50 simbols to be displayed in list view. -->
          <td><%= reminder.schedule.strftime("%Y-%m-%d %H:%M:00") %></td> 
          <td><%= reminder.created_at.strftime("%Y-%m-%d %H:%M:00") %></td>
        </tr>
      <% end %>
     </tbody>
  </table>
</div>
<div class="optlink">
  <%= submit_tag "Delete selected", data: { confirm: 'Are you sure want to delete selected?' } %>
  <% end %>
</div>
</html>

app/views/reminds/listallsentreminders.html.erb
<html>
  <div class="pad">
    <div id="header_text">
      <h2>List of all Past Reminders(<span style="color:red; font-family:Arial;">admin</span>)</h2><br>
      <h3 style="color:red"><%= flash[:notice] %></h3>
      <%= form_tag(listallsentreminders_path, :method => "get") do %>
        <%= text_field_tag :search, nil, :placeholder =>"E-mail address" %>
        <%= submit_tag "Search" %>
      <% end %>
    </div><br>
    <%= link_to 'List Scheduled Reminders', listallreminders_path %>
    <%= form_tag destroy_multiple_reminds_path, method: :delete do %> <!-- Form for selecting multiple reminders to delete. -->
    <table>
      <thead style="text-decoration: underline;">
          <th>Select to delete</th>
          <th>Email address</th>
          <th>Subject</th>
          <th>Was sent on</th>
          <th>Created on</th>
    
        </tr>
      </thead>
    
      <tbody>
        <% @reminders.where(:sent => true).each do |reminder| %> <!-- List only already sent reminders (where "sent" = true) -->
          <tr>
            <td><%= check_box_tag "reminds[]", reminder.id %></td>
            <td><%= Email.find_by_id(reminder.email_id).email %></td>
            <td><%= truncate(reminder.title, :length => 50) %></td> <!-- Allow only 50 simbols to be displayed in list view. -->
            <td><%= reminder.schedule.strftime("%Y-%m-%d %H:%M:00") %></td> 
            <td><%= reminder.created_at.strftime("%Y-%m-%d %H:%M:00") %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <div class="optlink">
    <%= submit_tag "Delete selected", data: { confirm: 'Are you sure want to delete selected?' } %>
    <% end %>
  </div>
</html>

app/views/reminds/new.html.erb
<h1>New Reminder</h1>
<div class="pad">
    <%= render 'form', remind: @remind %>
</div>
<div class="optlink">
    <%= link_to 'Back', :back %>
</div>

app/views/reminds/show.html.erb
<p id="notice"><%= notice %></p>
<div class="pad">
  <% if current_user.email == Email.find_by_id(@remind.email_id).email %> <!-- Validating if reminder belongs to the user who requested to view it -->
    <p>
      <strong>Scheduled for:</strong>
      <% Time.use_zone(Profile.find_by_user_id(current_user.id).timezone) do %>
        <%= @remind.schedule.strftime("%Y-%m-%d %H:%M %Z") %>
      <% end %>
    </p>
    
    <p>
      <strong>Title:</strong>
      <div class="mailmeta">
        <%= @remind.title %>
      </div>
    </p>
    
    <p>
      <strong>Body:</strong>
      <div class='mail'>
      <%= @remind.body.html_safe %>
      </div>
    </p>
  <% else %>
    <h2>You are not authorized to view this reminder.</h2>
  <% end %>
</div>
<div class="optlink">
  <%= link_to 'Back', :back %> | 
  <%= link_to 'Edit', edit_remind_path(@remind) %>
</div>